"""Build the committed play-by-play test fixture from a downloaded game.

``data/raw/`` is gitignored, so the test suite cannot depend on it. Instead we
commit one small, real slice of play-by-play under ``tests/fixtures/`` and test
against that, which keeps the suite runnable offline and on a fresh clone.

The slice is chosen to stay small while still containing every event category
the schema test cares about: period boundaries, scoring plays, fouls, free
throws, timeouts, turnovers, rebounds, and jump balls.

Run (after scripts/phase1_poc.py has downloaded a game):
    python scripts/make_test_fixture.py 0022300061
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.paths import PLAY_BY_PLAY_DIR, TESTS_FIXTURE_DIR, ensure_dir  # noqa: E402

FIXTURE_NAME = "playbyplay_sample.json"

# Event categories that must appear in the fixture for the schema test to be
# meaningful. Matched case-insensitively against actionType.
REQUIRED_ACTION_TYPES = [
    "period",
    "Jump Ball",
    "Made Shot",
    "Missed Shot",
    "Rebound",
    "Free Throw",
    "Foul",
    "Turnover",
    "Timeout",
]

HEAD_EVENTS = 60  # opening run of the game, kept contiguous
TAIL_EVENTS = 20  # closing sequence, where clock/score matter most
PER_CATEGORY = 4  # extra examples of each required category


def build_fixture(game_id: str) -> dict:
    source = PLAY_BY_PLAY_DIR / f"{game_id}.json"
    if not source.exists():
        raise SystemExit(f"No downloaded game at {source}. Run scripts/phase1_poc.py first.")

    raw = json.loads(source.read_text(encoding="utf-8"))
    actions = raw["game"]["actions"]

    keep: dict[int, dict] = {}

    def add(action: dict) -> None:
        keep[action["actionNumber"]] = action

    for action in actions[:HEAD_EVENTS]:
        add(action)
    for action in actions[-TAIL_EVENTS:]:
        add(action)

    for category in REQUIRED_ACTION_TYPES:
        matches = [a for a in actions if str(a.get("actionType", "")).lower() == category.lower()]
        for action in matches[:PER_CATEGORY]:
            add(action)

    selected = sorted(keep.values(), key=lambda a: a["actionNumber"])

    return {
        "meta": {
            "note": (
                "Trimmed slice of a real PlayByPlayV3 response, generated by "
                "scripts/make_test_fixture.py. Not a complete game."
            ),
            "sourceGameId": raw["game"]["gameId"],
            "originalActionCount": len(actions),
        },
        "game": {
            "gameId": raw["game"]["gameId"],
            "videoAvailable": raw["game"].get("videoAvailable", 0),
            "actions": selected,
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Create the play-by-play test fixture")
    parser.add_argument("game_id", help="GAME_ID already downloaded into data/raw/playbyplay/")
    args = parser.parse_args()

    fixture = build_fixture(args.game_id)
    ensure_dir(TESTS_FIXTURE_DIR)
    out = TESTS_FIXTURE_DIR / FIXTURE_NAME
    out.write_text(json.dumps(fixture, indent=2), encoding="utf-8")

    actions = fixture["game"]["actions"]
    print(f"Wrote {out}")
    print(f"  events kept : {len(actions)} of {fixture['meta']['originalActionCount']}")
    print(f"  periods     : {sorted({a['period'] for a in actions})}")
    types = sorted({str(a.get('actionType', '')).strip() or '(blank)' for a in actions})
    print(f"  actionTypes : {types}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
